dir 'plugin_gems'
download "specific_install", "0.3.1"
download "httpclient", "2.7.1"
download "td-client", "0.8.78"
download "td", "0.13.2"
download "fluent-plugin-td", "0.10.28"
download "thrift", "0.8.0"
download "fluent-plugin-scribe", "0.10.14"
download "uuidtools", "2.1.5"
download "bson", "1.12.5"
download "bson_ext", "1.12.5"
download "mongo", "1.12.5"
download "fluent-plugin-mongo", "0.7.12"
download "aws-sdk", "2.2.14"
download "aws-sdk-v1", "1.66.0"
download "fluent-plugin-s3", "0.6.5"
download "webhdfs", "0.7.4"
download "fluent-plugin-webhdfs", "0.4.1"
download "string-scrub", "0.0.5"
download "fluent-plugin-rewrite-tag-filter", "1.5.4"
download "fluent-plugin-td-monitoring", "0.2.2"

download "fluent-plugin-dstat", "0.3.1"
download "fluent-plugin-datadog_event", "0.1.2"
download "fluent-plugin-dogstatsd", "0.0.5"
download "fluent-plugin-elasticsearch", "1.4.0"
download "fluent-plugin-file-alternative", "0.2.2"
download "fluent-plugin-filter_typecast", "0.0.2"
download "fluent-plugin-flowcounter", "0.4.1"
download "fluent-plugin-forest", "0.3.0"
download "fluent-plugin-grep", "0.3.4"
# use custom version n0ts/fluent-plugin-map/my-develop
#download "fluent-plugin-map", ""
download "fluent-plugin-multiprocess", "0.2.0"
download "fluent-plugin-record-modifier", "0.4.1"
download "fluent-plugin-record-reformer", "0.8.1"
download "fluent-plugin-sampling-filter", "0.2.0"
download "fluent-plugin-typecast", "0.2.0"
download "dogapi", "1.21.0"

github "n0ts/fluent-plugin-map", "my-develop", "fluent-plugin-map-0.0.5"
